name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Pythonセットアップ
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: 必要パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: 静的検査（flake8）
        run: |
          flake8 . --count --show-source --statistics --exclude=./test_*.py
      - name: テストファイルの一覧
        run: ls ./test_*.py
      - name: テスト（pytest）
        run: |
          pytest test_*.py --junitxml='report.xml'
      - uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: './report.xml'
      - uses: mikepenz/action-junit-report@v6.4.1
        with:
          report_paths: ./report.xml
